### ISSUE TITLE
Has anyone successfully run the demo in macOS?

### ISSUE THREAD

**Issue by Steve-Tod** [StanfordVL/robovat#3]
Hi, I download the code and install with pip. When running the demo `python tools/sawyer_cli.py --mode sim`, I meet the following error:
If I enter `v` or `c`:
```
python[21276:85838] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fb8e5a126c0
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fb8e5a126c0'
```
Then `terminating with uncaught exception of type NSException`.

It seems this `NSInvalidArgumentException` is related to macOS interfaces... Has anyone successfully run the demo in macOS? Did you meet the same problem? Or the code is only runnable in Linux?

**Comment by infinitespace** [comment]
Exactly the same error for me. "g" "o" works but "v" "c" will crash the program with error:

2020-11-19 21:41:01.456 python[26891:4219922] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fb7e4ef3a10
2020-11-19 21:41:01.457 python[26891:4219922] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fb7e4ef3a10'
*** First throw call stack:

**Comment by leobxpan** [comment]
In case this is still of interest - this issue seems to be a bug when using pybullet and matplotlib together on mac (see https://github.com/bulletphysics/bullet3/issues/2125). 

I can temporarily get around it by adding 

```
import matplotlib.pyplot as plt
plt.figure()
```

before L47 in `robovat/robovat/simulation/bullet_physics.py`. But definitely not so elegant and hoping for a better solution.

**Comment by leobxpan** [comment]
Maybe @kuanfang if this workaround wants to be included to account for mac users.
